'use client';
import { ArrowDown, ArrowUpRight, Heart, Sparkles } from 'lucide-react';
export default function Home() {
return <main id="top">
<header className="site-header"><a className="brand" href="#top">a little world<span>just for you</span></a><a className="header-note" href="#letter">Made with all my heart <Heart size={15}/></a></header>
<section className="hero" aria-labelledby="hero-title">
<div className="hero-copy"><p className="eyebrow"><span/> ONE PERSON. A THOUSAND LITTLE FEELINGS.</p><h1 id="hero-title">Some people<br/>make the world<br/><em>more beautiful.</em></h1><p className="intro">For me, that person is you.</p><p className="hero-description">So I made you a little corner of the universe.<br/>A place where every detail says what my heart<br className="desktop-break"/> has been trying to put into words.</p><a className="letter-link" href="#letter">A little letter for you <ArrowUpRight size={19}/></a><div className="hero-foot"><span>Especially you. Always you.</span><a href="#little-things" aria-label="Discover more"><ArrowDown size={18}/></a></div></div>
<div className="portrait-stage"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span aria-hidden="true" className="portrait-star star-one">✦</span><span aria-hidden="true" className="portrait-star star-two">✧</span><div className="portrait-card" onPointerMove={e=>{if(e.pointerType==='mouse' && !window.matchMedia('(prefers-reduced-motion: reduce)').matches){const b=e.currentTarget.getBoundingClientRect();const x=((e.clientX-b.left)/b.width-.5)*10;const y=(.5-(e.clientY-b.top)/b.height)*8;e.currentTarget.style.transform='rotateY('+x+'deg) rotateX('+y+'deg)';}}} onPointerLeave={e=>{e.currentTarget.style.transform='';}}><img src="/portrait.png" alt="A cinematic three-dimensional interpretation of you in your pink floral sari" fetchPriority="high"/><div className="portrait-caption"><span>my favorite kind of magic</span><Heart size={19}/></div></div><div className="floating-note">If beauty were a feeling,<br/><em>it would feel like you.</em></div><span className="image-index">01 / A LITTLE PIECE OF FOREVER</span></div>
</section>
<section className="little-things" id="little-things"><p className="eyebrow">IT’S THE LITTLE THINGS</p><h2>More than a beautiful face.<br/><em>A beautiful reason to smile.</em></h2><div className="feelings"><article><span className="number">01</span><h3>The way you are.</h3><p>You don’t have to do anything extraordinary to be special to me. Just being yourself is already more than enough.</p></article><article><span className="number">02</span><h3>The thought of you.</h3><p>Somewhere in the middle of an ordinary day, you cross my mind — and suddenly, that day feels a little less ordinary.</p></article><article><span className="number">03</span><h3>The world with you in it.</h3><p>I like knowing that, out of all the places and all the moments in the world, I get to be here, thinking of you.</p></article></div></section>
<section className="letter-section" id="letter"><div className="letter-aside"><Sparkles size={24}/><p>A FEW WORDS,<br/>FROM THE HEART.</p><span>For you,<br/><em>with love.</em></span></div><article className="letter"><span className="eyebrow">SOMETHING I WANTED YOU TO KNOW</span><h2>Dear you,</h2><p>I wanted to make something beautiful for you. Then I realized the most beautiful part was already there — you.</p><p>There is a quiet kind of magic in the way you make me feel. The thought of you brings a softness to my day that I can’t quite explain, but never want to lose.</p><p>If I could give you one thing, it would be a moment to see yourself through my eyes. You would understand why even the simplest picture of you can make me stop and smile.</p><p>I hope life is gentle with you. I hope you have a hundred little reasons to laugh, people who listen, and room to become everything you dream of being. And I hope this little corner of the world reminds you that someone is very, very glad you exist.</p><p className="letter-ending">You don’t need to be perfect.<br/><em>You being you is my favorite part.</em></p><div className="signature">With all my heart <Heart size={19}/></div></article></section>
<footer><a href="#top">a little world, just for you.</a><span>Every word meant. Every detail, for you. <Heart size={14}/></span></footer>
</main>;
}
